title: "Data-Driven Science: a Python Visual and Practical Text Book"
author: Yliess HATI
copyright: "2020"
logo: "../resources/cover_square.png"

execute:
  execute_notebooks: "auto"
  
repository:
  url: https://github.com/yliess86/DataDrivenScienceBook
  
html:
  favicon: "../resources/cover_favicon.ico"
  use_repository_button: true
  use_issues_button: true