title: "Data-Driven Science: a Python Visual and Practical Text Book"
author: Yliess HATI
copyright: "2020"

execute:
  execute_notebooks: "force"
  
repository:
  url: https://github.com/yliess86/DataDrivenScienceBook
  
html:
  use_repository_button: true